### ISSUE TITLE
Using large number of concurrent requests 

### ISSUE THREAD

**Issue by rootart** [mduygu/slowsloth#1]
Thank you for the interesting project! 👍 
I tried running it against the local service and found that concurrent requests aren't working as expected. The command `./SlowSloth -u http://localhost:9001/courses -m GET -c 100 -delay 10 ` doesn't create the expected number of connections. 

Is there a way to get more details regarding the current test's state while it is running?  So far this is the only thing I'm receiving 
```
Total active connections: 100
Service availability: truee
Total RAM usage: 12 MB
```
Many thanks 🎄

**Comment by mduygu** [comment]
Hey @rootart,

Thank you for your feedback. If you are using a system like Mac or Linux, you can instantly see the open connections on the port where the application is running on your system by using the following command. I will examine in detail if there is a specific problem with Localhost. Here is an example for you:

`sudo lsof -i :9001 | wc -l | awk '{print $1-1}'`

<img width="967" alt="get_portcon" src="https://github.com/mduygu/slowsloth/assets/61627415/e44fd82b-a56e-4e56-bfea-53319808b594">

Please contact me for more details and information.

Cheers.
